In [20]:
# # Description
# 
# Prove that the Noise Reduction model works on a 2D polinomial.

# Add libs folder path to system variables to make the importation of local libraries easier.
# __________________________________________________________________________________________________
import os
import sys


CURRENT_DIR = os.getcwd()
FOLDERS = CURRENT_DIR.split(os.sep)
TESIS_FOLDER_INDEX = FOLDERS.index('S-noise-gradient')
CURRENT_DIR = os.sep.join(FOLDERS[:TESIS_FOLDER_INDEX+1])
LIBS_PATH = os.path.join(CURRENT_DIR, 'src', 'libs')
assert os.path.exists(LIBS_PATH)
sys.path.append(LIBS_PATH)


# Import external and local libraries
# __________________________________________________________________________________________________
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import torch
import torch.nn as nn
import torch.optim as optim
import json
from typing import List

# Locals
from utils import *
from dataset import Dataset
from models import *
import config as cfg
from dlnr import DLNoiseReduction


# Global / Path variables
# __________________________________________________________________________________________________
DATA_PATH = os.path.join(CURRENT_DIR, 'data')
CHECKPOINT_PATH = os.path.join(CURRENT_DIR, 'checkpoints')
CONFIG_PATH = os.path.join(CURRENT_DIR, 'config')


# Make sure that the GPU is being used
# __________________________________________________________________________________________________
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
assert device.type == "cuda"

In [21]:
def add_gaussian_noise(df:pd.DataFrame, columns:List[str], mean:float = 0.0, std:float = 0.1):
    """
    Adds Gaussian noise to specified columns in a DataFrame.

    Args:
        df (pandas.DataFrame): The DataFrame to which noise will be added.
        columns (list): A list of column names in the DataFrame to which noise will be added.
        mean (int, optional): The mean of the Gaussian distribution. Defaults to 0.
        std (float, optional): The standard deviation of the Gaussian distribution. Defaults to 0.1.

    Returns:
        pandas.DataFrame: The DataFrame with added Gaussian noise to specified columns.
    """
    for col in columns:
        df[col] = df[col] + np.random.normal(loc=mean, scale=std, size=len(df))
    return df

In [22]:
data = np.arange(0, 100, 0.01)
data_df = pd.DataFrame(data, columns=['x'])
data_df['y'] = data_df['x']

scaler = MinMaxScaler()
data_df = pd.DataFrame(scaler.fit_transform(data_df), columns=['x', 'y'])

In [23]:
data_df

           x       y
0     0.0000  0.0000
1     0.0001  0.0001
2     0.0002  0.0002
3     0.0003  0.0003
4     0.0004  0.0004
...      ...     ...
9995  0.9996  0.9996
9996  0.9997  0.9997
9997  0.9998  0.9998
9998  0.9999  0.9999
9999  1.0000  1.0000

[10000 rows x 2 columns]

In [24]:
data_original = data_df.copy()
for sigma in np.arange(0.01, 0.012, 0.01):
        print(1)
        df_noisy = add_gaussian_noise(
                df=data_original.copy(),
                columns=['x'],
                mean=0.0,
                std=sigma
        )
        data_df = pd.concat([data_df, df_noisy])

1

In [25]:
data_df = df_noisy

In [26]:
data_df

             x       y
0     0.015321  0.0000
1    -0.002859  0.0001
2    -0.000089  0.0002
3     0.004884  0.0003
4    -0.002896  0.0004
...        ...     ...
9995  1.003554  0.9996
9996  1.012572  0.9997
9997  1.001934  0.9998
9998  0.994379  0.9999
9999  0.996312  1.0000

[10000 rows x 2 columns]

In [27]:
batch_size = 168 # 1 week of data (24*7)

In [28]:
# data_df = data_df.sample(fr
# 
# ac=1).reset_index(drop=True)
print(data_df)
limit = int(len(data_df)%batch_size)
data_df = data_df.iloc[:-limit]

             x       y
0     0.015321  0.0000
1    -0.002859  0.0001
2    -0.000089  0.0002
3     0.004884  0.0003
4    -0.002896  0.0004
...        ...     ...
9995  1.003554  0.9996
9996  1.012572  0.9997
9997  1.001934  0.9998
9998  0.994379  0.9999
9999  0.996312  1.0000

[10000 rows x 2 columns]

In [29]:
data_df

             x         y
0     0.015321  0.000000
1    -0.002859  0.000100
2    -0.000089  0.000200
3     0.004884  0.000300
4    -0.002896  0.000400
...        ...       ...
9907  0.982241  0.990799
9908  0.974634  0.990899
9909  0.984846  0.990999
9910  1.014876  0.991099
9911  0.975295  0.991199

[9912 rows x 2 columns]

In [30]:
# Create Datasets for DataLoaders
noisy_dataset = Dataset(
    input_df=data_df['x'],
    target_df=data_df['y']
)

# Create the dataloaders
train_dataloader = DataLoader(noisy_dataset, batch_size=batch_size, shuffle=True, num_workers=0)

In [31]:
denoiser = DenoisingAutoencoder(
    input_dim=batch_size,
    latent_dim=64,
).to(device)

In [32]:
for x in train_dataloader:
    print(x)
    break

[tensor([ 0.7335,  0.8770,  0.2825,  0.5421,  0.6989,  0.4987,  0.7023,  0.5514,
         0.5925,  0.1876,  0.6082,  0.4983,  0.1794,  0.7261,  0.9630,  0.1003,
         0.2761,  0.6577,  0.2451,  0.2600,  0.4521,  0.7667,  0.3922,  0.4809,
         0.6126,  0.1941,  0.1703,  0.4118,  0.3753,  0.8141,  0.6583,  0.4450,
         0.9114,  0.6698,  0.7951,  0.7840,  0.3530,  0.7784,  0.3655,  0.6709,
         0.4119,  0.0568,  0.2060,  0.4545,  0.4293,  0.6855,  0.4501,  0.1001,
         0.6584,  0.0181,  0.2164,  0.4143,  0.2605,  0.7391,  0.4840,  0.0227,
         0.7006,  0.6026,  0.6647,  0.7730,  0.2821,  0.0382,  0.8182,  0.3719,
         0.6612,  0.3026,  0.6191,  0.8510,  0.0571,  0.6881,  0.9370,  0.8838,
         0.1429,  0.5393,  0.8665,  0.1401,  0.5599,  0.5556,  0.7230,  0.3586,
         0.1861,  0.3657,  0.1473,  0.6734,  0.8062,  0.3523,  0.3149,  0.3646,
         0.1882,  0.5066,  0.8861,  0.8122,  0.0621,  0.6077,  0.9745,  0.9202,
         0.8684,  0.1805,  0.1225,  0.2546,  0.2013,  0.1796,  0.4490,  0.4556,
         0.0208,  0.7360,  0.5876,  0.6466,  0.7623,  0.9124,  0.1515,  0.1065,
         0.4962,  0.0402,  0.6504,  0.4314,  0.7220,  0.3237,  0.9638,  0.9576,
         0.0149,  0.1496,  0.8082,  0.8699,  0.3362,  0.8334,  0.0049,  0.8365,
         0.6449,  0.4467,  0.9204,  0.4084, -0.0157,  0.7288,  0.3977,  0.8408,
         0.9258,  0.4319,  0.8980,  0.4363,  0.2211,  0.1293,  0.6647,  0.7678,
         0.9214,  0.0311,  0.6812,  0.7483,  0.9752,  0.3940,  0.8293,  0.5477,
         0.5017,  0.3417,  0.2974,  0.3812,  0.4936,  0.9733,  0.9012,  0.5983,
         0.4231,  0.3211,  0.8997,  0.3315,  0.5203,  0.4286,  0.5895,  0.1530]), tensor([7.3427e-01, 9.1689e-01, 2.7413e-01, 5.3335e-01, 7.0147e-01, 5.0615e-01,
        6.9827e-01, 5.5416e-01, 5.8716e-01, 1.9672e-01, 6.0076e-01, 4.8795e-01,
        1.7192e-01, 7.0697e-01, 9.6610e-01, 1.0921e-01, 2.7233e-01, 6.5357e-01,
        2.5103e-01, 2.4402e-01, 4.4624e-01, 7.5948e-01, 3.8754e-01, 4.7325e-01,
        6.0186e-01, 2.0782e-01, 1.8032e-01, 3.9984e-01, 3.6534e-01, 8.0738e-01,
        6.4126e-01, 4.4534e-01, 9.0599e-01, 6.6537e-01, 8.1328e-01, 7.7578e-01,
        3.6234e-01, 7.6848e-01, 3.5854e-01, 6.7537e-01, 4.2804e-01, 5.6206e-02,
        1.9982e-01, 4.6095e-01, 4.2084e-01, 6.8267e-01, 4.4634e-01, 9.1809e-02,
        6.6567e-01, 1.5002e-02, 2.3842e-01, 4.1954e-01, 2.6663e-01, 7.2887e-01,
        4.8155e-01, 1.1401e-02, 7.0097e-01, 5.9536e-01, 6.8477e-01, 7.8318e-01,
        2.8213e-01, 5.6606e-02, 8.0188e-01, 3.8154e-01, 6.3966e-01, 2.9653e-01,
        6.2496e-01, 8.3978e-01, 8.7109e-02, 6.8797e-01, 9.4349e-01, 8.8689e-01,
        1.5462e-01, 5.1685e-01, 8.7779e-01, 1.4761e-01, 5.5866e-01, 5.5326e-01,
        7.2527e-01, 3.5784e-01, 1.8732e-01, 3.8944e-01, 1.3691e-01, 6.8377e-01,
        8.0238e-01, 3.4113e-01, 3.1673e-01, 3.6894e-01, 1.8332e-01, 5.0965e-01,
        8.7679e-01, 8.1868e-01, 5.7206e-02, 6.1046e-01, 9.7950e-01, 9.2829e-01,
        8.6209e-01, 1.6172e-01, 1.1531e-01, 2.4162e-01, 1.9372e-01, 1.8892e-01,
        4.3744e-01, 4.5805e-01, 3.9204e-02, 7.2327e-01, 5.7476e-01, 6.5477e-01,
        7.8078e-01, 9.2329e-01, 1.5792e-01, 1.0691e-01, 5.0495e-01, 3.5004e-02,
        6.4926e-01, 4.1934e-01, 7.1347e-01, 3.2443e-01, 9.5020e-01, 9.5330e-01,
        2.7303e-02, 1.3651e-01, 8.0948e-01, 8.7559e-01, 3.4733e-01, 8.2868e-01,
        3.0003e-04, 8.3238e-01, 6.3776e-01, 4.3104e-01, 9.2479e-01, 4.0714e-01,
        1.5002e-03, 7.3787e-01, 4.0194e-01, 8.4528e-01, 9.1449e-01, 4.3484e-01,
        9.0709e-01, 4.2764e-01, 2.2502e-01, 1.2741e-01, 6.6987e-01, 7.6498e-01,
        9.2119e-01, 2.6603e-02, 6.5867e-01, 7.2827e-01, 9.7000e-01, 3.8524e-01,
        8.3518e-01, 5.6296e-01, 4.9665e-01, 3.4873e-01, 3.1353e-01, 3.8634e-01,
        4.7845e-01, 9.7360e-01, 8.9409e-01, 5.8456e-01, 4.2394e-01, 3.1303e-01,
        9.1189e-01, 3.3303e-01, 5.3435e-01, 4.3124e-01, 6.0706e-01, 1.3751e-01])]

In [33]:
data_df

             x         y
0     0.015321  0.000000
1    -0.002859  0.000100
2    -0.000089  0.000200
3     0.004884  0.000300
4    -0.002896  0.000400
...        ...       ...
9907  0.982241  0.990799
9908  0.974634  0.990899
9909  0.984846  0.990999
9910  1.014876  0.991099
9911  0.975295  0.991199

[9912 rows x 2 columns]

In [34]:
# Set model parameters and create the model Trainer object
lr = 0.001
criterion = nn.MSELoss()
optimizer = optim.Adam(denoiser.parameters(), lr=lr)

# Define the trainer
trainer_basic = Trainer(
    model=denoiser,
    train_generator=train_dataloader,
    val_generator=train_dataloader,
    device=device,
    criterion=criterion,
    optimizer=optimizer,
    epoch_scheduler=None,
    batch_scheduler=None,
    patience=15,
    epochs=500,
    checkpoints_path=os.path.join(
        CHECKPOINT_PATH, 'denoising_autoencoder'
    ),
)

In [35]:
# denoiser = torch.load(os.path.join(CHECKPOINT_PATH, 'denoising_autoencoder.pth'))

In [36]:
# Train the model
model, train_losses, val_losses, best_train_loss, best_val_loss = trainer_basic.fit(verbose=True)

Training is started!

Epochs loop:  20%|▏| 100/500 [02:08<08:32,  1.28s/epoch, Train loss: 0.0819854689604145 - Va

Training stopped as validation loss did not improve for 15 epochs.

In [37]:
y_pred_noisy = trainer_basic.eval_dataloader(train_dataloader)
flattened_tensor = torch.cat(y_pred_noisy).view(-1)
len(flattened_tensor)

9912

In [38]:
# Show the metrics
gt_values = data_df['y'].values
predicted_values = flattened_tensor.cpu().detach().numpy()

mae = mean_absolute_error(gt_values, predicted_values)
mse = mean_squared_error(gt_values, predicted_values)
rmse = np.sqrt(mse)
# mape = np.mean(np.abs(gt_values - predicted_values) / gt_values) * 100
r_squared = r2_score(gt_values, predicted_values)
nn_benchmark = {
    'nn': {
        "MSE: ": mse,
        "RMSE: ": rmse,
        "MAE: ": mae,
        # "MAPE: ": mape,
        "R2: ": r_squared
    }
}
nn_benchmark

{'nn': {'MSE: ': 0.08300265680698475,
  'RMSE: ': 0.288101816736696,
  'MAE: ': 0.24851536204334007,
  'R2: ': -0.013593447401432313}}