In [1]:
import os
import sys

CURRENT_DIR = os.getcwd()
FOLDERS = CURRENT_DIR.split(os.sep)
TESIS_FOLDER_INDEX = FOLDERS.index('S-noise-gradient')
CURRENT_DIR = os.sep.join(FOLDERS[:TESIS_FOLDER_INDEX+1])
LIBS_PATH = os.path.join(CURRENT_DIR, 'src', 'libs')
assert os.path.exists(LIBS_PATH)
sys.path.append(LIBS_PATH)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Locals
from utils import *
from dataset import Dataset
from models import *
from dlnr import DLNoiseReduction

In [3]:
DATA_PATH = os.path.join(CURRENT_DIR, 'data')
CHECKPOINT_PATH = os.path.join(CURRENT_DIR, 'checkpoints')
CONFIG_PATH = os.path.join(CURRENT_DIR, 'config')

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
assert device.type == "cuda"

In [17]:
df = pd.read_csv(os.path.join(DATA_PATH, 'Informer_Datasets', 'WTH', 'WTH.csv'))
df

,date,Visibility,DryBulbFarenheit,DryBulbCelsius,WetBulbFarenheit,DewPointFarenheit,DewPointCelsius,RelativeHumidity,WindSpeed,WindDirection,StationPressure,Altimeter,WetBulbCelsius
0,1/1/2010 0:00,10.0,16,-9,13,7,-14,67,7,130,21.650000,30.35,-10.3
1,1/1/2010 1:00,10.0,16,-9,13,7,-14,67,5,150,21.640000,30.34,-10.3
2,1/1/2010 2:00,10.0,16,-9,13,7,-14,67,5,190,21.650000,30.35,-10.3
3,1/1/2010 3:00,10.0,16,-9,13,7,-14,67,7,180,21.650000,30.35,-10.3
4,1/1/2010 4:00,10.0,16,-9,14,9,-13,74,6,120,21.640000,30.34,-10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35059,12/31/2013 19:00,10.0,32,0,0,23,-5,0,0,0,21.478686,30.21,0.0
35060,12/31/2013 20:00,7.0,30,-1,0,25,-4,0,5,110,21.478686,30.21,0.0
35061,12/31/2013 21:00,5.0,30,-1,0,28,-2,0,0,0,21.478686,30.20,0.0
35062,12/31/2013 22:00,10.0,30,-1,0,28,-2,0,5,140,21.478686,30.18,0.0
35063,12/31/2013 23:00,10.0,30,-1,29,28,-2,92,5,110,21.520000,30.18,-1.5

In [5]:
df = pd.read_csv(os.path.join(DATA_PATH, 'Informer_Datasets', 'ETT', 'ETTh1.csv'))
df.tail()

                      date    HUFL   HULL   MUFL   MULL   LUFL   LULL      OT
17415  2018-06-26 15:00:00  -1.674  3.550 -5.615  2.132  3.472  1.523  10.904
17416  2018-06-26 16:00:00  -5.492  4.287 -9.132  2.274  3.533  1.675  11.044
17417  2018-06-26 17:00:00   2.813  3.818 -0.817  2.097  3.716  1.523  10.271
17418  2018-06-26 18:00:00   9.243  3.818  5.472  2.097  3.655  1.432   9.778
17419  2018-06-26 19:00:00  10.114  3.550  6.183  1.564  3.716  1.462   9.567

In [6]:
df.index = pd.to_datetime(df['date'])
df.drop(columns=['date'], inplace=True)
df.describe().T

,count,mean,std,min,25%,50%,75%,max
HUFL,17420.0,7.375141,7.067744,-22.705999,5.827,8.774,11.788,23.643999
HULL,17420.0,2.242242,2.042342,-4.756000,0.737,2.210,3.684,10.114000
MUFL,17420.0,4.300239,6.826978,-25.087999,3.296,5.970,8.635,17.341000
MULL,17420.0,0.881568,1.809293,-5.934000,-0.284,0.959,2.203,7.747000
LUFL,17420.0,3.066062,1.164506,-1.188000,2.315,2.833,3.625,8.498000
LULL,17420.0,0.856932,0.599552,-1.371000,0.670,0.975,1.218,3.046000
OT,17420.0,13.324672,8.566946,-4.080000,6.964,11.396,18.079,46.007000

In [7]:
X = df[df.columns[:-1]]
y = df[df.columns[-1:]]

In [8]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled.describe().T

        count      mean       std  min       25%       50%       75%  max
HUFL  17420.0  0.649000  0.152486  0.0  0.615599  0.679180  0.744207  1.0
HULL  17420.0  0.470628  0.137346  0.0  0.369401  0.468460  0.567586  1.0
MUFL  17420.0  0.692645  0.160904  0.0  0.668976  0.731999  0.794810  1.0
MULL  17420.0  0.498178  0.132249  0.0  0.412982  0.503837  0.594766  1.0
LUFL  17420.0  0.439197  0.120226  0.0  0.361656  0.415135  0.496903  1.0
LULL  17420.0  0.504399  0.135737  0.0  0.462078  0.531130  0.586144  1.0

In [9]:
# Dividir en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [10]:
X_train = torch.tensor(X_train.values, dtype=torch.float32).to(device)
X_val = torch.tensor(X_val.values, dtype=torch.float32).to(device)
X_test = torch.tensor(X_test.values, dtype=torch.float32).to(device)
y_train = torch.tensor(y_train.values, dtype=torch.float32).to(device)
y_val = torch.tensor(y_val.values, dtype=torch.float32).to(device)
y_test = torch.tensor(y_test.values, dtype=torch.float32).to(device)

In [11]:
# Agregar una dimensión adicional para los timesteps (necesario para GRU)
X_train = X_train.unsqueeze(1)  # Añadir dimensión para "timesteps"
X_val = X_val.unsqueeze(1)
X_test = X_test.unsqueeze(1)

In [12]:
input_size = len(X_scaled.columns)  # Número de variables de entrada
hidden_size = 50  # Número de unidades en la GRU
output_size = len(y.columns)  # Predicción de una variable
num_layers = 1  # Una sola capa GRU

# Crear el modelo
model = LSTMModel(input_size, hidden_size, output_size, num_layers).to(device)

# Definir la función de pérdida y el optimizador
criterion = nn.MSELoss()  # Error cuadrático medio
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [13]:
train_dataloader = DataLoader(TensorDataset(X_train, y_train), batch_size=64, shuffle=True)
val_dataloader = DataLoader(TensorDataset(X_val, y_val), batch_size=64, shuffle=False)
test_dataloader = DataLoader(TensorDataset(X_test, y_test), batch_size=64, shuffle=False)

In [14]:
trainer = Trainer(
    model = model,
    train_generator = train_dataloader,
    val_generator = val_dataloader,
    device = device,
    criterion = criterion,
    optimizer = optimizer,
    epoch_scheduler = None,
    batch_scheduler = None,
    patience = 10,
    epochs = 100,
    checkpoints_path = os.path.join(CHECKPOINT_PATH, 'ETT', 'gru.pth'),
)

In [15]:
trainer.fit(verbose=True)

Training is started!

Epochs loop:   0%|         | 0/100 [00:00<?, ?epoch/s]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [ ]:
predictions = trainer.eval_dataloader(test_dataloader)

In [ ]:
predictions = torch.cat(predictions, dim=0)
predictions.shape

torch.Size([3484, 1])

In [ ]:
np.sqrt(criterion(predictions, y_test).cpu().detach().numpy())

8.279524

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
HUFL,17420.0,7.375141,7.067744,-22.705999,5.827,8.774,11.788,23.643999
HULL,17420.0,2.242242,2.042342,-4.756000,0.737,2.210,3.684,10.114000
MUFL,17420.0,4.300239,6.826978,-25.087999,3.296,5.970,8.635,17.341000
MULL,17420.0,0.881568,1.809293,-5.934000,-0.284,0.959,2.203,7.747000
LUFL,17420.0,3.066062,1.164506,-1.188000,2.315,2.833,3.625,8.498000
LULL,17420.0,0.856932,0.599552,-1.371000,0.670,0.975,1.218,3.046000
OT,17420.0,13.324672,8.566946,-4.080000,6.964,11.396,18.079,46.007000